version: '3.8'

services:
  # База даних PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: whitty_db
    restart: always
    environment:
      POSTGRES_USER: itssayzy
      POSTGRES_PASSWORD: IvanVitkovskiy2006
      POSTGRES_DB: itssayzy
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Інтерфейс для перегляду бази даних (як MongoDB Compass, але для SQL)
  pgadmin:
    image: dpage/pgadmin4
    container_name: whitty_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data: