

services:
  
  app:
    build: .             
    container_name: whitty_app
    restart: always
    ports:
      - '8080:8080'      
    environment:
      
      DATABASE_URL: "postgresql://itssayzy:IvanVitkovskiy2006@postgres:5432/itssayzy?schema=public"
      JWT_SECRET: "mySuperSecretKey123" 
      PORT: 8080
    depends_on:
      - postgres        
    volumes:
      - ./uploads:/app/uploads 

  
  postgres:
    image: postgres:15-alpine
    container_name: whitty_db
    restart: always
    environment:
      POSTGRES_USER: itssayzy
      POSTGRES_PASSWORD: IvanVitkovskiy2006
      POSTGRES_DB: itssayzy
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  
  pgadmin:
    image: dpage/pgadmin4
    container_name: whitty_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data: